//! One independent `#[test]` per `tests/*.zu` fixture (generated by
//! `build.rs`, see that file's own docs) that has a matching
//! `tests/*.out` file. Each runs the compiled `zuri` binary on its
//! fixture and checks combined stdout+stderr for an exact match, with
//! `@@ROOT` in the expected output resolved to this checkout's own
//! canonical root; the same check `tmp/run_zu_tests.sh` did by hand,
//! now wired into `cargo test`, with per-fixture pass/fail instead of
//! one aggregate result.

use std::fs;
use std::process::Command;

fn run_fixture(zu_path_str: &str) {
  let manifest_dir = env!("CARGO_MANIFEST_DIR");
  let bin = env!("CARGO_BIN_EXE_zuri");
  let root = fs::canonicalize(manifest_dir)
    .expect("crate root should be canonicalizable")
    .display()
    .to_string();

  let out_path_str = format!(
    "{}.out",
    zu_path_str.strip_suffix(".zu").unwrap_or(zu_path_str)
  );
  let expected_raw = fs::read_to_string(&out_path_str)
    .unwrap_or_else(|e| panic!("failed to read {out_path_str}: {e}"));
  let expected = expected_raw.replace("@@ROOT", &root);

  // Shells out through `sh -c '... 2>&1'` (rather than capturing
  // stdout/stderr as separate pipes and concatenating them
  // afterward) specifically to preserve TRUE chronological
  // interleaving between echoed output and an eventual uncaught-
  // error message; exactly what the original script's
  // `"$BIN" "$zu" 2>&1` gave for free via real shell redirection.
  let output = Command::new("sh")
    .arg("-c")
    .arg(format!(
      "{} {} 2>&1",
      shell_quote(bin),
      shell_quote(zu_path_str)
    ))
    .output()
    .unwrap_or_else(|e| panic!("failed to run zuri on {zu_path_str}: {e}"));
  let actual = String::from_utf8_lossy(&output.stdout).into_owned();

  // Both sides went through a `$(...)` command substitution in the
  // original script, which strips ALL trailing newlines; match that
  // so a lone trailing-newline difference isn't a false failure.
  let actual = actual.trim_end_matches('\n');
  let expected = expected.trim_end_matches('\n');
  assert_eq!(
    actual, expected,
    "\n{zu_path_str}\n--- expected ---\n{expected}\n--- actual ---\n{actual}\n"
  );
}

fn shell_quote(s: &str) -> String {
  format!("'{}'", s.replace('\'', r"'\''"))
}

// Generated by `build.rs` into `tests/generated/`; a subdirectory,
// not `tests/` itself, so Cargo's top-level test auto-discovery
// doesn't also try (and fail) to compile it as its own standalone
// integration-test binary. See `build.rs`'s own docs on why this path
// is fixed (computable from `CARGO_MANIFEST_DIR` alone) rather than
// routed through `OUT_DIR`.
include!(concat!(
  env!("CARGO_MANIFEST_DIR"),
  "/tests/generated/zu_conformance_generated.rs"
));
