//! One independent `#[test]` per `.zu` fixture with a matching `.out`
//! file (generated by `build.rs`, see that file's own docs). A
//! top-level `tests/*.zu` fixture gets an exact stdout+stderr match
//! against its `.out` (`run_fixture`), with `@@ROOT` resolved to this
//! checkout's own canonical root. A fixture in a subdirectory instead
//! gets `run_exit_code_fixture`: its own suite decides pass/fail
//! internally (self-checking assertions, raising on the first real
//! failure) and prints whatever it wants along the way, so the only
//! thing worth asserting from outside is that the process didn't exit
//! non-zero; a golden-output diff would be either infeasible (variable
//! timing, generated keys, wall-clock-dependent behavior) or just
//! redundant with checks the fixture already does itself.

use std::fs;
use std::io::Read;
use std::process::{Child, Command, ExitStatus, Stdio};
use std::sync::{Arc, Mutex, mpsc};
use std::time::{Duration, Instant};

fn run_fixture(zu_path_str: &str) {
  let manifest_dir = env!("CARGO_MANIFEST_DIR");
  // Through the same helper the runtime itself uses, so both sides
  // spell a canonical path identically. Windows' own canonical form
  // carries a `\\?\` prefix that the runtime strips before any of it
  // reaches a diagnostic; expanding `@@ROOT` with the unstripped form
  // would leave the expected text disagreeing with the actual on
  // nothing but that prefix.
  let root = zuri::builtins::file::canonical_path(manifest_dir)
    .expect("crate root should be canonicalizable");

  let out_path_str = format!(
    "{}.out",
    zu_path_str.strip_suffix(".zu").unwrap_or(zu_path_str)
  );
  let expected_raw = fs::read_to_string(&out_path_str)
    .unwrap_or_else(|e| panic!("failed to read {out_path_str}: {e}"));
  let expected = expected_raw.replace("@@ROOT", &root);

  let (_, actual) = run_zuri(zu_path_str);

  // Both sides went through a `$(...)` command substitution in the
  // original script, which strips ALL trailing newlines; match that
  // so a lone trailing-newline difference isn't a false failure.
  //
  // Carriage returns go too. A `.gitattributes` rule keeps the `.out`
  // files LF on every platform, but a checkout made with a different
  // git configuration would otherwise fail every golden-output test on
  // a line ending that was never in the repository. No fixture holds a
  // carriage return on purpose, so dropping them costs no coverage.
  let actual = actual.replace("\r\n", "\n");
  let expected = expected.replace("\r\n", "\n");

  // Separators go the same way, for the same reason.
  //
  // A fixture spells every path after `@@ROOT` with a forward slash,
  // but `@@ROOT` expands to a native path, so the expected text ends up
  // mixing both while the runtime's own diagnostics use native
  // separators throughout. The two then differ on nothing but the
  // slashes. No `.out` file in the suite contains a backslash for any
  // other purpose, so on Windows every one of them is a separator and
  // normalising them masks nothing.
  #[cfg(windows)]
  let actual = actual.replace('\\', "/");
  #[cfg(windows)]
  let expected = expected.replace('\\', "/");

  let actual = actual.trim_end_matches(['\n', '\r']);
  let expected = expected.trim_end_matches(['\n', '\r']);
  assert_eq!(
    actual, expected,
    "\n{zu_path_str}\n--- expected ---\n{expected}\n--- actual ---\n{actual}\n"
  );
}

fn run_exit_code_fixture(zu_path_str: &str) {
  let (status, output) = run_zuri(zu_path_str);
  assert!(
    status.success(),
    "\n{zu_path_str} exited with {status}\n--- output ---\n{output}\n"
  );
}

/// The most resident memory a fixture may hold before it is stopped.
/// A fixture that leaks fails on its own this way, long before it can
/// exhaust the memory of the machine running the suite.
const MEMORY_CAP_BYTES: u64 = 2 << 30;

/// How often a running fixture's memory is checked against the cap.
const MEMORY_POLL: Duration = Duration::from_millis(5);

/// The longest a fixture may run before it is stopped. No fixture
/// has any business running this long, so one that reaches it is
/// hung, and stopping it gets its output into the failure instead of
/// holding the whole suite until the job is killed.
const FIXTURE_TIMEOUT: Duration = Duration::from_secs(180);

/// How long a stopped fixture's output is waited for. A process the
/// fixture started can still hold the pipe open after the fixture
/// itself is gone, and then whatever has arrived by now is all there is.
const OUTPUT_GRACE: Duration = Duration::from_secs(5);

/// Runs the executable on one fixture, returning how it exited and
/// everything it printed.
///
/// Stdout and stderr share a single pipe, so echoed output and an
/// uncaught-error message arrive in the order they were written. The
/// executable is spawned directly, with no shell in between, so the
/// process held to `MEMORY_CAP_BYTES` and `FIXTURE_TIMEOUT` is the
/// fixture itself.
fn run_zuri(zu_path_str: &str) -> (ExitStatus, String) {
  let (mut output, writer) = std::io::pipe().expect("failed to create the output pipe");
  let mut child = Command::new(env!("CARGO_BIN_EXE_zuri"))
    .arg("run")
    .arg(zu_path_str)
    .stdin(Stdio::null())
    .stdout(writer.try_clone().expect("failed to share the output pipe"))
    .stderr(writer)
    .spawn()
    .unwrap_or_else(|e| panic!("failed to run zuri on {zu_path_str}: {e}"));

  // Drained on its own thread, since a fixture that fills the pipe
  // would otherwise block on its next write while this one waits for
  // it to exit. What it reads is kept where this thread can see it
  // before the pipe closes, so a stopped fixture still reports what
  // it printed.
  let collected = Arc::new(Mutex::new(Vec::new()));
  let (drained, all_drained) = mpsc::channel();
  let sink = Arc::clone(&collected);
  std::thread::spawn(move || {
    let mut chunk = [0u8; 8192];
    while let Ok(n @ 1..) = output.read(&mut chunk) {
      sink.lock().unwrap().extend_from_slice(&chunk[..n]);
    }
    let _ = drained.send(());
  });

  let started = Instant::now();
  let mut stopped = None;
  let status = loop {
    if let Some(status) = child.try_wait().expect("failed to poll a fixture") {
      break status;
    }
    if resident_bytes(&child).is_some_and(|bytes| bytes > MEMORY_CAP_BYTES) {
      stopped = Some(format!(
        "stopped after passing {} MB resident",
        MEMORY_CAP_BYTES >> 20
      ));
    } else if started.elapsed() > FIXTURE_TIMEOUT {
      stopped = Some(format!(
        "stopped after running for {} seconds",
        FIXTURE_TIMEOUT.as_secs()
      ));
    }
    if stopped.is_some() {
      let _ = child.kill();
      break child.wait().expect("failed to reap a fixture");
    }
    std::thread::sleep(MEMORY_POLL);
  };

  // A fixture that exited on its own closed its end of the pipe, so
  // the rest of its output is on the way and worth waiting for.
  match stopped {
    None => all_drained.recv().expect("the output collector panicked"),
    Some(_) => {
      let _ = all_drained.recv_timeout(OUTPUT_GRACE);
    },
  }

  let bytes = collected.lock().unwrap();
  let mut text = String::from_utf8_lossy(&bytes).into_owned();
  if let Some(reason) = stopped {
    text.push_str(&format!("\n--- {reason} ---\n"));
  }

  (status, text)
}

#[cfg(any(target_os = "linux", target_os = "android"))]
fn resident_bytes(child: &Child) -> Option<u64> {
  let statm = fs::read_to_string(format!("/proc/{}/statm", child.id())).ok()?;
  let pages: u64 = statm.split_whitespace().nth(1)?.parse().ok()?;
  let page_size = unsafe { libc::sysconf(libc::_SC_PAGESIZE) };

  Some(pages * page_size as u64)
}

#[cfg(target_vendor = "apple")]
fn resident_bytes(child: &Child) -> Option<u64> {
  let mut info: libc::proc_taskinfo = unsafe { std::mem::zeroed() };
  let size = size_of::<libc::proc_taskinfo>() as libc::c_int;
  let written = unsafe {
    libc::proc_pidinfo(
      child.id() as libc::c_int,
      libc::PROC_PIDTASKINFO,
      0,
      (&raw mut info).cast(),
      size,
    )
  };

  (written == size).then_some(info.pti_resident_size)
}

#[cfg(windows)]
fn resident_bytes(child: &Child) -> Option<u64> {
  use std::os::windows::io::AsRawHandle;
  use windows_sys::Win32::System::ProcessStatus::{
    K32GetProcessMemoryInfo, PROCESS_MEMORY_COUNTERS,
  };

  let mut counters: PROCESS_MEMORY_COUNTERS = unsafe { std::mem::zeroed() };
  let size = size_of::<PROCESS_MEMORY_COUNTERS>() as u32;
  counters.cb = size;
  let ok = unsafe { K32GetProcessMemoryInfo(child.as_raw_handle(), &mut counters, size) };

  (ok != 0).then_some(counters.WorkingSetSize as u64)
}

/// Other platforms have no reader here, and their fixtures run
/// uncapped.
#[cfg(not(any(
  target_os = "linux",
  target_os = "android",
  target_vendor = "apple",
  windows
)))]
fn resident_bytes(_child: &Child) -> Option<u64> {
  None
}

// Generated by `build.rs` into `tests/generated/`; a subdirectory,
// not `tests/` itself, so Cargo's top-level test auto-discovery
// doesn't also try (and fail) to compile it as its own standalone
// integration-test binary. See `build.rs`'s own docs on why this path
// is fixed (computable from `CARGO_MANIFEST_DIR` alone) rather than
// routed through `OUT_DIR`.
include!(concat!(
  env!("CARGO_MANIFEST_DIR"),
  "/tests/generated/zu_conformance_generated.rs"
));

/// The launch rules the executable implements: `zuri run` for scripts
/// and packages, a bare first word for a command. Each case builds the
/// tree it needs under Cargo's own test temp directory, so nothing
/// here depends on the shape of the checkout it runs in.
mod launch {
  use std::fs;
  use std::path::{Path, PathBuf};
  use std::process::{Command, Output};

  /// A fresh directory for one case, named after it so a failure says
  /// where to look.
  fn case(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
      .join("launch")
      .join(name);

    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("failed to create the case directory");

    dir
  }

  fn write(path: &Path, source: &str) {
    if let Some(parent) = path.parent() {
      fs::create_dir_all(parent).expect("failed to create a fixture directory");
    }

    fs::write(path, source).expect("failed to write a fixture");
  }

  /// Runs the built executable from `cwd`, with stderr folded in so a
  /// launch failure is as readable as ordinary output.
  fn zuri(cwd: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_zuri"))
      .args(args)
      .current_dir(cwd)
      .output()
      .expect("failed to run zuri")
  }

  fn combined(output: &Output) -> String {
    let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stderr));

    text.replace("\r\n", "\n")
  }

  /// Asserts the executable aborted with the house launch-failure
  /// message naming `name` and `reason`.
  fn assert_aborted(output: &Output, name: &str, reason: &str) {
    let text = combined(output);
    let expected = format!("  Launch aborted for {name}\n  Reason: {reason}");

    assert!(
      text.contains("(Zuri):") && text.contains(&expected),
      "\n--- expected to contain ---\n{expected}\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1), "launch failures exit 1");
  }

  fn assert_ran(output: &Output, expected: &str) {
    let text = combined(output);

    assert!(
      output.status.success(),
      "\n{} did not exit cleanly\n--- output ---\n{text}\n",
      env!("CARGO_BIN_EXE_zuri")
    );
    assert!(
      text.contains(expected),
      "\n--- expected to contain ---\n{expected}\n--- actual ---\n{text}\n"
    );
  }

  /// Reports the arguments the script was handed, which is the shape
  /// `os.args[2,]` is documented to have.
  const REPORT_ARGS: &str = "import os\n\necho 'ran ${os.args[2,]}'\n";

  #[test]
  fn version_reports_the_build_without_running_anything() {
    let dir = case("version");
    // An entrypoint that would announce itself if `--version` were ever
    // read as a path or a command.
    write(&dir.join("index.zu"), "echo 'ran the entrypoint'\n");

    let output = zuri(&dir, &["--version"]);
    let text = combined(&output);

    assert!(output.status.success(), "--version must exit 0\n{text}");
    assert!(
      !text.contains("ran the entrypoint"),
      "--version must not launch anything\n--- actual ---\n{text}\n"
    );

    // The same two lines the REPL opens with, minus its own note that
    // it is interactive.
    let mut lines = text.lines();
    let version = lines.next().unwrap_or_default();

    assert!(
      version.starts_with("Zuri ") && version.contains("(running on ZuriVM "),
      "\n--- actual ---\n{text}\n"
    );
    assert!(
      !version.contains("REPL"),
      "--version must not claim to be interactive\n--- actual ---\n{text}\n"
    );
    assert!(
      lines
        .next()
        .unwrap_or_default()
        .starts_with("Build No. => "),
      "\n--- actual ---\n{text}\n"
    );
  }

  /// The line a help listing gives one command, without its indent.
  fn listed<'a>(text: &'a str, name: &str) -> Option<&'a str> {
    text
      .lines()
      .map(str::trim_end)
      .find(|line| line.starts_with(&format!("  {name}")))
      .map(|line| line.trim_start())
  }

  /// A command that says what it is, the way a real one does.
  fn command_source(name: &str, description: &str) -> String {
    format!("/**\n * @command {name}\n * @description {description}\n */\n\necho 'ran {name}'\n")
  }

  #[test]
  fn help_lists_the_commands_the_runtime_ships() {
    let dir = case("help_shipped");
    // Would announce itself if `--help` ever launched anything.
    write(&dir.join("index.zu"), "echo 'ran the entrypoint'\n");

    let output = zuri(&dir, &["--help"]);
    let text = combined(&output);

    assert!(output.status.success(), "--help must exit 0\n{text}");
    assert!(
      !text.contains("ran the entrypoint"),
      "--help must not launch anything\n--- actual ---\n{text}\n"
    );

    // It opens with what `--version` reports, then the usage.
    assert!(text.starts_with("Zuri "), "\n--- actual ---\n{text}\n");
    assert!(text.contains("Build No. => "), "\n--- actual ---\n{text}\n");
    assert!(text.contains("Usage: zuri"), "\n--- actual ---\n{text}\n");
    assert!(text.contains("\nCOMMANDS:\n"), "\n--- actual ---\n{text}\n");

    // `fmt` ships in `cmds/`, and must arrive described.
    let line = listed(&text, "fmt")
      .unwrap_or_else(|| panic!("fmt was not listed\n--- actual ---\n{text}\n"));

    assert!(
      line.len() > "fmt".len(),
      "fmt was listed with no description: {line:?}"
    );
  }

  #[test]
  fn the_short_flags_match_the_long_ones() {
    let dir = case("short_flags");

    assert_eq!(
      combined(&zuri(&dir, &["-h"])),
      combined(&zuri(&dir, &["--help"])),
      "-h must print exactly what --help prints"
    );
    assert_eq!(
      combined(&zuri(&dir, &["-v"])),
      combined(&zuri(&dir, &["--version"])),
      "-v must print exactly what --version prints"
    );
  }

  #[test]
  fn help_lists_a_projects_own_commands() {
    let dir = case("help_project");
    write(
      &dir.join(".zuri/cmds/lint.zu"),
      &command_source("lint", "Check the project for the mistakes CI rejects."),
    );
    // A description long enough to wrap, which is written as an
    // indented continuation of the tag.
    write(
      &dir.join(".zuri/cmds/deploy/index.zu"),
      "/**\n * @command deploy\n * @description Ship the current build to staging,\n *    then wait for the health check.\n */\n",
    );

    let output = zuri(&dir, &["--help"]);
    let text = combined(&output);

    assert!(
      text.contains("\nPROJECT COMMANDS:\n"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(
      listed(&text, "lint"),
      Some("lint    Check the project for the mistakes CI rejects."),
      "\n--- actual ---\n{text}\n"
    );

    // The wrapped continuation arrives joined onto one line.
    assert_eq!(
      listed(&text, "deploy"),
      Some("deploy  Ship the current build to staging, then wait for the health check."),
      "\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn help_leaves_out_a_project_command_a_shipped_one_hides() {
    let dir = case("help_shadowed");
    write(
      &dir.join(".zuri/cmds/fmt.zu"),
      &command_source("fmt", "The project copy, which can never run."),
    );

    let text = combined(&zuri(&dir, &["--help"]));

    assert!(
      !text.contains("The project copy"),
      "a command that can never run was listed\n--- actual ---\n{text}\n"
    );
    assert!(
      !text.contains("PROJECT COMMANDS"),
      "the section must go entirely when it would be empty\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn help_lists_a_command_that_describes_nothing() {
    let dir = case("help_undescribed");
    write(&dir.join(".zuri/cmds/bare.zu"), "echo 'bare'\n");

    let text = combined(&zuri(&dir, &["--help"]));

    assert_eq!(
      listed(&text, "bare"),
      Some("bare"),
      "a command with no doc block must still be listed by name\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn run_uses_the_working_directory_entrypoint() {
    let dir = case("run_cwd_entry");
    write(&dir.join("index.zu"), REPORT_ARGS);

    assert_ran(&zuri(&dir, &["run"]), "ran []");
  }

  #[test]
  fn run_without_an_entrypoint_aborts() {
    let dir = case("run_cwd_no_entry");
    let output = zuri(&dir, &["run"]);

    // The working directory is named in full, since the user typed no
    // path for the message to quote back.
    let text = combined(&output);
    assert!(
      text.contains("Reason: No entrypoint found in the directory"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
  }

  #[test]
  fn run_launches_a_script() {
    let dir = case("run_script");
    write(&dir.join("main.zu"), REPORT_ARGS);

    assert_ran(&zuri(&dir, &["run", "main.zu"]), "ran []");
  }

  #[test]
  fn run_launches_a_directory_entrypoint() {
    let dir = case("run_directory");
    write(&dir.join("package").join("index.zu"), REPORT_ARGS);

    assert_ran(&zuri(&dir, &["run", "package"]), "ran []");
  }

  #[test]
  fn run_on_a_directory_without_an_entrypoint_aborts() {
    let dir = case("run_directory_no_entry");
    fs::create_dir_all(dir.join("package")).expect("failed to create the package directory");

    assert_aborted(
      &zuri(&dir, &["run", "package"]),
      "package",
      "No entrypoint found in the directory",
    );
  }

  #[test]
  fn run_on_a_missing_path_aborts() {
    let dir = case("run_missing");

    assert_aborted(
      &zuri(&dir, &["run", "nowhere.zu"]),
      "nowhere.zu",
      "No such file or directory",
    );
  }

  #[test]
  fn run_on_a_file_that_is_not_a_script_aborts() {
    let dir = case("run_not_a_script");
    write(&dir.join("notes.txt"), "echo 'hello'\n");

    assert_aborted(
      &zuri(&dir, &["run", "notes.txt"]),
      "notes.txt",
      "Not a Zuri script",
    );
  }

  #[test]
  fn run_forwards_the_rest_to_the_script() {
    let dir = case("run_forwards");
    write(&dir.join("main.zu"), REPORT_ARGS);

    assert_ran(
      &zuri(&dir, &["run", "main.zu", "build", "--force", "-n"]),
      "ran [build, --force, -n]",
    );
  }

  #[test]
  fn a_flag_after_run_belongs_to_the_entrypoint() {
    let dir = case("run_leading_flag");
    write(&dir.join("index.zu"), REPORT_ARGS);

    assert_ran(&zuri(&dir, &["run", "--force"]), "ran [--force]");
  }

  #[test]
  fn a_project_command_runs_from_a_script() {
    let dir = case("command_script");
    write(&dir.join(".zuri/cmds/greet.zu"), REPORT_ARGS);

    assert_ran(
      &zuri(&dir, &["greet", "world", "--loud"]),
      "ran [world, --loud]",
    );
  }

  #[test]
  fn a_project_command_runs_from_a_directory() {
    let dir = case("command_directory");
    write(&dir.join(".zuri/cmds/greet/index.zu"), REPORT_ARGS);

    assert_ran(&zuri(&dir, &["greet", "world"]), "ran [world]");
  }

  #[test]
  fn a_command_directory_wins_over_a_command_file() {
    let dir = case("command_directory_precedence");
    write(&dir.join(".zuri/cmds/greet.zu"), "echo 'ran the file'\n");
    write(&dir.join(".zuri/cmds/greet/index.zu"), REPORT_ARGS);

    let output = zuri(&dir, &["greet", "world"]);
    let text = combined(&output);

    assert!(
      !text.contains("ran the file"),
      "a command file shadowed the directory beside it\n--- actual ---\n{text}\n"
    );
    assert_ran(&output, "ran [world]");
  }

  #[test]
  fn a_command_directory_without_an_entrypoint_is_not_a_command() {
    let dir = case("command_directory_no_entry");
    fs::create_dir_all(dir.join(".zuri/cmds/greet")).expect("failed to create the command");

    assert_aborted(&zuri(&dir, &["greet"]), "greet", "Unknown command");
  }

  #[test]
  fn a_command_file_answers_for_an_empty_directory_beside_it() {
    let dir = case("command_directory_falls_through");
    write(&dir.join(".zuri/cmds/greet.zu"), REPORT_ARGS);
    fs::create_dir_all(dir.join(".zuri/cmds/greet")).expect("failed to create the command");

    assert_ran(&zuri(&dir, &["greet", "world"]), "ran [world]");
  }

  #[test]
  fn a_shipped_command_wins_over_a_project_one() {
    let dir = case("command_precedence");
    write(&dir.join(".zuri/cmds/fmt.zu"), "echo 'the project copy'\n");

    let output = zuri(&dir, &["fmt", "--help"]);
    let text = combined(&output);

    assert!(
      !text.contains("the project copy"),
      "a project command shadowed one the runtime ships\n--- actual ---\n{text}\n"
    );
    assert_ran(&output, "Usage: fmt");
  }

  #[test]
  fn an_unknown_command_aborts() {
    let dir = case("command_unknown");

    assert_aborted(&zuri(&dir, &["nowhere"]), "nowhere", "Unknown command");
  }

  #[test]
  fn a_path_never_names_a_command() {
    let dir = case("command_traversal");
    write(&dir.join(".zuri/cmds/greet.zu"), REPORT_ARGS);

    // Both spellings would resolve inside the command directory if the
    // name were joined onto it unchecked.
    assert_aborted(&zuri(&dir, &["./greet"]), "./greet", "Unknown command");
    assert_aborted(
      &zuri(&dir, &["../cmds/greet"]),
      "../cmds/greet",
      "Unknown command",
    );
  }

  #[test]
  fn a_script_is_not_launched_as_a_command() {
    let dir = case("command_is_not_a_path");
    write(&dir.join("main.zu"), REPORT_ARGS);

    // `run` is the only way to reach a file; a bare path is a command
    // name that happens to contain a dot.
    assert_aborted(&zuri(&dir, &["main.zu"]), "main.zu", "Unknown command");
  }
}

/// The `test` command end to end: the tree it finds, the one file a
/// name picks out, and the status a failing run leaves behind. The
/// rules themselves are covered in Zuri, under `cmds/test/tests`;
/// this is here to prove the command the runtime ships reaches them.
mod test_command {
  use std::fs;
  use std::path::{Path, PathBuf};
  use std::process::{Command, Output};

  fn write(path: &Path, source: &str) {
    if let Some(parent) = path.parent() {
      fs::create_dir_all(parent).expect("failed to create a fixture directory");
    }

    fs::write(path, source).expect("failed to write a fixture");
  }

  /// A project with one passing file, one failing file, and one a
  /// level down, so discovery and reporting both have something to
  /// say.
  fn project(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
      .join("test_command")
      .join(name);

    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("failed to create the case directory");

    write(
      &dir.join("tests/pass.zu"),
      "import test { * }\n\nit('passes', @{\n  expect(1).to_equal(1)\n})\n",
    );
    write(
      &dir.join("tests/fail.zu"),
      "import test { * }\n\nit('fails', @{\n  expect(1).to_equal(2)\n})\n",
    );
    write(
      &dir.join("tests/deep/nested.zu"),
      "import test { * }\n\nit('is nested', @{\n  expect(true).to_be_truthy()\n})\n",
    );

    dir
  }

  fn zuri(cwd: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_zuri"))
      .args(args)
      .current_dir(cwd)
      .env("NO_COLOR", "1")
      .output()
      .expect("failed to run zuri")
  }

  fn combined(output: &Output) -> String {
    let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stderr));

    text.replace("\r\n", "\n")
  }

  #[test]
  fn it_conducts_the_tests_directory() {
    let dir = project("whole");
    let output = zuri(&dir, &["test"]);
    let text = combined(&output);

    for name in ["pass.zu", "fail.zu", "nested.zu"] {
      assert!(
        text.contains(name),
        "{name} never ran\n--- actual ---\n{text}\n"
      );
    }

    assert_eq!(
      output.status.code(),
      Some(1),
      "a failing file must leave a failing status\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn a_name_picks_out_one_file_with_or_without_its_extension() {
    let dir = project("one_file");

    for target in ["pass", "pass.zu"] {
      let output = zuri(&dir, &["test", target]);
      let text = combined(&output);

      assert!(
        output.status.success(),
        "`zuri test {target}` did not exit cleanly\n--- actual ---\n{text}\n"
      );
      assert!(
        text.contains("pass.zu") && !text.contains("fail.zu"),
        "`zuri test {target}` ran the wrong files\n--- actual ---\n{text}\n"
      );
    }
  }

  #[test]
  fn a_name_reaches_into_a_subdirectory() {
    let dir = project("nested");
    let output = zuri(&dir, &["test", "nested"]);
    let text = combined(&output);

    assert!(
      output.status.success() && text.contains("nested.zu"),
      "\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn list_prints_the_files_and_runs_none_of_them() {
    let dir = project("listing");
    let output = zuri(&dir, &["test", "--list"]);
    let text = combined(&output);

    let listed: Vec<&str> = text.lines().filter(|line| !line.is_empty()).collect();
    let expected: Vec<String> = ["tests/deep/nested.zu", "tests/fail.zu", "tests/pass.zu"]
      .iter()
      .map(|path| path.replace('/', std::path::MAIN_SEPARATOR_STR))
      .collect();

    assert_eq!(listed, expected, "\n--- actual ---\n{text}\n");
    assert!(output.status.success(), "--list must exit 0\n{text}");
  }

  #[test]
  fn a_name_that_matches_nothing_is_refused() {
    let dir = project("missing");
    let output = zuri(&dir, &["test", "nowhere"]);
    let text = combined(&output);

    assert!(
      text.contains("test: there is no test file or directory named 'nowhere'"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
  }

  #[test]
  fn a_project_with_no_tests_directory_is_told_so() {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
      .join("test_command")
      .join("empty");

    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("failed to create the case directory");

    let output = zuri(&dir, &["test"]);
    let text = combined(&output);

    assert!(
      text.contains("there is no 'tests' directory here"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
  }
}

/// The `init` command end to end: the tree it writes, the project that
/// tree turns out to be, and what it refuses to do twice. The rules
/// themselves are covered in Zuri, under `cmds/init/tests`; this is
/// here to prove the command the runtime ships reaches them, and that
/// what it scaffolds actually runs.
mod init_command {
  use std::fs;
  use std::path::{Path, PathBuf};
  use std::process::{Command, Output};

  /// An empty directory to initialize a project in or under.
  fn case(name: &str) -> PathBuf {
    let dir = Path::new(env!("CARGO_TARGET_TMPDIR"))
      .join("init_command")
      .join(name);

    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("failed to create the case directory");

    dir
  }

  fn zuri(cwd: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_zuri"))
      .args(args)
      .current_dir(cwd)
      .env("NO_COLOR", "1")
      .output()
      .expect("failed to run zuri")
  }

  fn combined(output: &Output) -> String {
    let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
    text.push_str(&String::from_utf8_lossy(&output.stderr));

    text.replace("\r\n", "\n")
  }

  fn read(path: &Path) -> String {
    fs::read_to_string(path).unwrap_or_else(|_| panic!("{} was never written", path.display()))
  }

  /// Every file the layout promises, as paths under the project root.
  const LAYOUT: [&str; 7] = [
    "project.toml",
    "index.zu",
    "app/index.zu",
    "tests/app.test.zu",
    "README.md",
    ".gitignore",
    ".gitattributes",
  ];

  #[test]
  fn it_writes_the_whole_layout() {
    let dir = case("layout");
    let output = zuri(&dir, &["init", "myproject", "--yes", "--vcs", "none"]);
    let text = combined(&output);

    assert!(
      output.status.success(),
      "init did not exit cleanly\n--- actual ---\n{text}\n"
    );

    let root = dir.join("myproject");

    for path in LAYOUT {
      assert!(
        root.join(path).is_file(),
        "{path} was never written\n--- actual ---\n{text}\n"
      );
    }

    assert!(
      read(&root.join("project.toml")).contains("name = \"myproject\""),
      "the manifest was not named after the project"
    );
  }

  #[test]
  fn what_it_writes_runs_and_passes_its_own_tests() {
    let dir = case("runnable");

    zuri(&dir, &["init", "app", "--yes", "--vcs", "none"]);

    let root = dir.join("app");
    let run = zuri(&root, &["run"]);
    let ran = combined(&run);

    assert!(
      run.status.success() && ran.contains("Hello, world!"),
      "the scaffolded project did not run\n--- actual ---\n{ran}\n"
    );

    let tested = zuri(&root, &["test"]);
    let report = combined(&tested);

    assert!(
      tested.status.success(),
      "the scaffolded tests did not pass\n--- actual ---\n{report}\n"
    );
  }

  #[test]
  fn what_it_writes_is_already_formatted() {
    let dir = case("formatted");

    zuri(&dir, &["init", "app", "--yes", "--vcs", "none"]);

    let root = dir.join("app");
    let output = zuri(&root, &["fmt", "--dry-run", "."]);
    let text = combined(&output);

    assert!(
      output.status.success(),
      "the scaffolded source was not in the project style\n--- actual ---\n{text}\n"
    );
  }

  #[test]
  fn with_no_path_it_initializes_where_it_stands() {
    let dir = case("here");
    let output = zuri(&dir, &["init", "--yes", "--vcs", "none"]);
    let text = combined(&output);

    assert!(
      output.status.success() && dir.join("project.toml").is_file(),
      "\n--- actual ---\n{text}\n"
    );
    assert!(
      read(&dir.join("project.toml")).contains("name = \"here\""),
      "the project was not named after the directory it went into"
    );
  }

  #[test]
  fn the_command_line_settles_what_it_would_otherwise_ask() {
    let dir = case("flags");

    let output = zuri(
      &dir,
      &[
        "init",
        "--yes",
        "--vcs",
        "none",
        "--name",
        "my-app",
        "--version",
        "2.1.0",
        "--description",
        "Does one thing.",
        "--license",
        "Apache-2.0",
        "--homepage",
        "https://example.com",
      ],
    );

    let text = combined(&output);
    assert!(output.status.success(), "\n--- actual ---\n{text}\n");

    let manifest = read(&dir.join("project.toml"));

    for line in [
      "name = \"my-app\"",
      "version = \"2.1.0\"",
      "description = \"Does one thing.\"",
      "license = \"Apache-2.0\"",
      "homepage = \"https://example.com\"",
    ] {
      assert!(
        manifest.contains(line),
        "{line} never reached the manifest\n--- actual ---\n{manifest}\n"
      );
    }
  }

  #[test]
  fn a_project_is_never_initialized_twice() {
    let dir = case("twice");

    zuri(&dir, &["init", "--yes", "--vcs", "none"]);

    let output = zuri(&dir, &["init", "--yes", "--vcs", "none"]);
    let text = combined(&output);

    assert!(
      text.contains("a project already exists"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
  }

  #[test]
  fn force_rewrites_the_manifest_and_leaves_the_rest() {
    let dir = case("force");

    zuri(&dir, &["init", "--yes", "--vcs", "none", "--name", "first"]);

    let output = zuri(
      &dir,
      &[
        "init", "--yes", "--vcs", "none", "--force", "--name", "second",
      ],
    );

    let text = combined(&output);
    assert!(output.status.success(), "\n--- actual ---\n{text}\n");

    assert!(
      read(&dir.join("project.toml")).contains("name = \"second\""),
      "the manifest was not written again"
    );
    assert!(
      read(&dir.join("README.md")).contains("# first"),
      "--force disturbed a file that was not the manifest"
    );
  }

  #[test]
  fn a_dry_run_reports_and_writes_nothing() {
    let dir = case("dry");
    let output = zuri(&dir, &["init", "--yes", "--vcs", "none", "--dry-run"]);
    let text = combined(&output);

    assert!(output.status.success(), "\n--- actual ---\n{text}\n");

    for path in LAYOUT {
      assert!(
        text.contains(path),
        "{path} was not reported\n--- actual ---\n{text}\n"
      );
      assert!(
        !dir.join(path).exists(),
        "{path} was written on a dry run\n--- actual ---\n{text}\n"
      );
    }
  }

  #[test]
  fn a_name_it_cannot_use_is_refused_before_anything_is_written() {
    let dir = case("bad_name");
    let output = zuri(&dir, &["init", "--yes", "--name", "My App"]);
    let text = combined(&output);

    assert!(
      text.contains("init: 'My App' cannot be used as a project name"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
    assert!(
      !dir.join("project.toml").exists(),
      "a refused name still wrote a project"
    );
  }

  #[test]
  fn a_version_it_cannot_use_is_refused_too() {
    let dir = case("bad_version");
    let output = zuri(&dir, &["init", "--yes", "--version", "1.2"]);
    let text = combined(&output);

    assert!(
      text.contains("init: '1.2' is not a valid version"),
      "\n--- actual ---\n{text}\n"
    );
    assert_eq!(output.status.code(), Some(1));
  }

  #[test]
  fn it_arrives_described_in_the_listing() {
    let dir = case("listed");
    let text = combined(&zuri(&dir, &["--help"]));

    let line = text
      .lines()
      .map(str::trim)
      .find(|line| line.starts_with("init"))
      .unwrap_or_else(|| panic!("init was not listed\n--- actual ---\n{text}\n"));

    assert!(
      line.len() > "init".len(),
      "init was listed with no description: {line:?}"
    );
  }
}
