//! One independent `#[test]` per `.zu` fixture with a matching `.out`
//! file (generated by `build.rs`, see that file's own docs). A
//! top-level `tests/*.zu` fixture gets an exact stdout+stderr match
//! against its `.out` (`run_fixture`), with `@@ROOT` resolved to this
//! checkout's own canonical root. A fixture in a subdirectory instead
//! gets `run_exit_code_fixture`: its own suite decides pass/fail
//! internally (self-checking assertions, raising on the first real
//! failure) and prints whatever it wants along the way, so the only
//! thing worth asserting from outside is that the process didn't exit
//! non-zero; a golden-output diff would be either infeasible (variable
//! timing, generated keys, wall-clock-dependent behavior) or just
//! redundant with checks the fixture already does itself.

use std::fs;
use std::process::Command;

fn run_fixture(zu_path_str: &str) {
  let manifest_dir = env!("CARGO_MANIFEST_DIR");
  let bin = env!("CARGO_BIN_EXE_zuri");
  // Through the same helper the runtime itself uses, so both sides
  // spell a canonical path identically. Windows' own canonical form
  // carries a `\\?\` prefix that the runtime strips before any of it
  // reaches a diagnostic; expanding `@@ROOT` with the unstripped form
  // would leave the expected text disagreeing with the actual on
  // nothing but that prefix.
  let root = zuri::builtins::file::canonical_path(manifest_dir)
    .expect("crate root should be canonicalizable");

  let out_path_str = format!(
    "{}.out",
    zu_path_str.strip_suffix(".zu").unwrap_or(zu_path_str)
  );
  let expected_raw = fs::read_to_string(&out_path_str)
    .unwrap_or_else(|e| panic!("failed to read {out_path_str}: {e}"));
  let expected = expected_raw.replace("@@ROOT", &root);

  // Shells out through `sh -c '... 2>&1'` (rather than capturing
  // stdout/stderr as separate pipes and concatenating them
  // afterward) specifically to preserve TRUE chronological
  // interleaving between echoed output and an eventual uncaught-
  // error message; exactly what the original script's
  // `"$BIN" "$zu" 2>&1` gave for free via real shell redirection.
  let output = Command::new("sh")
    .arg("-c")
    .arg(format!(
      "{} {} 2>&1",
      shell_quote(bin),
      shell_quote(zu_path_str)
    ))
    .output()
    .unwrap_or_else(|e| panic!("failed to run zuri on {zu_path_str}: {e}"));
  let actual = String::from_utf8_lossy(&output.stdout).into_owned();

  // Both sides went through a `$(...)` command substitution in the
  // original script, which strips ALL trailing newlines; match that
  // so a lone trailing-newline difference isn't a false failure.
  //
  // Carriage returns go too. A `.gitattributes` rule keeps the `.out`
  // files LF on every platform, but a checkout made with a different
  // git configuration would otherwise fail every golden-output test on
  // a line ending that was never in the repository. No fixture holds a
  // carriage return on purpose, so dropping them costs no coverage.
  let actual = actual.replace("\r\n", "\n");
  let expected = expected.replace("\r\n", "\n");

  // Separators go the same way, for the same reason.
  //
  // A fixture spells every path after `@@ROOT` with a forward slash,
  // but `@@ROOT` expands to a native path, so the expected text ends up
  // mixing both while the runtime's own diagnostics use native
  // separators throughout. The two then differ on nothing but the
  // slashes. No `.out` file in the suite contains a backslash for any
  // other purpose, so on Windows every one of them is a separator and
  // normalising them masks nothing.
  #[cfg(windows)]
  let actual = actual.replace('\\', "/");
  #[cfg(windows)]
  let expected = expected.replace('\\', "/");

  let actual = actual.trim_end_matches(['\n', '\r']);
  let expected = expected.trim_end_matches(['\n', '\r']);
  assert_eq!(
    actual, expected,
    "\n{zu_path_str}\n--- expected ---\n{expected}\n--- actual ---\n{actual}\n"
  );
}

fn run_exit_code_fixture(zu_path_str: &str) {
  let bin = env!("CARGO_BIN_EXE_zuri");
  let output = Command::new("sh")
    .arg("-c")
    .arg(format!(
      "{} {} 2>&1",
      shell_quote(bin),
      shell_quote(zu_path_str)
    ))
    .output()
    .unwrap_or_else(|e| panic!("failed to run zuri on {zu_path_str}: {e}"));
  assert!(
    output.status.success(),
    "\n{zu_path_str} exited with {}\n--- output ---\n{}\n",
    output.status,
    String::from_utf8_lossy(&output.stdout)
  );
}

fn shell_quote(s: &str) -> String {
  format!("'{}'", s.replace('\'', r"'\''"))
}

// Generated by `build.rs` into `tests/generated/`; a subdirectory,
// not `tests/` itself, so Cargo's top-level test auto-discovery
// doesn't also try (and fail) to compile it as its own standalone
// integration-test binary. See `build.rs`'s own docs on why this path
// is fixed (computable from `CARGO_MANIFEST_DIR` alone) rather than
// routed through `OUT_DIR`.
include!(concat!(
  env!("CARGO_MANIFEST_DIR"),
  "/tests/generated/zu_conformance_generated.rs"
));
