use std::{fmt, str::Utf8Error};
use zlib_rs::{Deflate, DeflateError, DeflateFlush, Inflate, InflateError, InflateFlush, Status};

const SCRATCH_SIZE: usize = 32 * 1024;

/// A streaming raw-DEFLATE encoder.
///
/// The encoder owns both its input and output buffering. The caller
/// never has to provide a scratch buffer to zlib-rs.
pub struct DeflateEncoder {
  deflate: Deflate,

  /// Input that has been accepted by `write()` but has not yet been
  /// consumed by the compressor.
  input: Vec<u8>,

  /// All compressed output generated by the compressor.
  ///
  /// `output_pos` points to the first byte that has not yet been
  /// returned by `take_output()`.
  output: Vec<u8>,
  output_pos: usize,

  /// Private scratch space passed to zlib-rs.
  scratch: Vec<u8>,

  finished: bool,
}

impl DeflateEncoder {
  /// Creates a raw-DEFLATE encoder.
  ///
  /// `level`:
  /// - 0: no compression
  /// - 1: fastest
  /// - 9: best compression
  /// - 6: normal/default compression
  pub fn new(level: i32, zlib_header: bool) -> Self {
    Self {
      // false = raw DEFLATE, without a zlib header.
      // 15    = 32 KiB DEFLATE window.
      deflate: Deflate::new(level, zlib_header, 15),

      input: Vec::new(),

      output: Vec::new(),
      output_pos: 0,

      scratch: vec![0; SCRATCH_SIZE],

      finished: false,
    }
  }

  // /// Creates an encoder using the default compression level.
  // pub fn default() -> Self {
  //   Self::new(6, false)
  // }

  /// Supplies uncompressed data to the encoder.
  ///
  /// All bytes are accepted into the encoder's internal buffer.
  ///
  /// The returned value is therefore normally exactly `input.len()`.
  /// Compressed data can be retrieved with `take_output()`.
  pub fn write(&mut self, input: &[u8]) -> Result<usize, DeflateError> {
    if self.finished {
      return Err(DeflateError::StreamError);
    }

    if input.is_empty() {
      return Ok(0);
    }

    self.input.extend_from_slice(input);

    self.process(DeflateFlush::NoFlush)?;

    Ok(input.len())
  }

  /// Flushes all currently pending compressed data.
  ///
  /// Unlike `finish()`, this does not terminate the DEFLATE stream.
  ///
  /// The returned bytes can be sent immediately to a streaming
  /// decompressor.
  pub fn flush(&mut self) -> Result<Vec<u8>, DeflateError> {
    if self.finished {
      return Err(DeflateError::StreamError);
    }

    // Make sure all accepted input has reached zlib-rs first.
    self.process(DeflateFlush::NoFlush)?;

    // SyncFlush forces zlib-rs to emit everything it has buffered.
    self.process(DeflateFlush::SyncFlush)?;

    Ok(self.take_output())
  }

  /// Finishes the DEFLATE stream and returns the remaining compressed
  /// output.
  ///
  /// After this method succeeds, the encoder cannot accept any more
  /// input.
  pub fn finish(&mut self) -> Result<Vec<u8>, DeflateError> {
    if self.finished {
      return Err(DeflateError::StreamError);
    }

    // Ensure every byte accepted by write() has been handed to
    // the compressor before terminating the stream.
    self.process(DeflateFlush::NoFlush)?;

    debug_assert!(
      self.input.is_empty(),
      "NoFlush must consume all pending input"
    );

    // Z_FINISH may require multiple calls when the scratch output
    // buffer is smaller than the final compressed output.
    loop {
      let before_out = self.deflate.total_out();

      let status = self
        .deflate
        .compress(&[], &mut self.scratch, DeflateFlush::Finish)?;

      let produced = (self.deflate.total_out() - before_out) as usize;

      self.append_scratch(produced);

      match status {
        Status::StreamEnd => {
          self.finished = true;
          return Ok(self.take_output());
        },

        Status::Ok | Status::BufError => {
          // The zlib API explicitly requires another Finish
          // call when StreamEnd wasn't reached.
          //
          // Our scratch buffer is available again, so simply
          // continue.
        },
      }
    }
  }

  pub fn reset(&mut self) -> Result<Vec<u8>, DeflateError> {
    let output = self.finish()?;
    self.deflate.reset();
    Ok(output)
  }

  /// Returns all compressed bytes currently waiting to be consumed.
  ///
  /// This does not flush the compressor. If `write()` was called with
  /// data that zlib-rs has buffered internally, this may return fewer
  /// bytes than expected (including zero bytes).
  pub fn take_output(&mut self) -> Vec<u8> {
    if self.output_pos == 0 {
      return std::mem::take(&mut self.output);
    }

    if self.output_pos == self.output.len() {
      self.output.clear();
      self.output_pos = 0;
      return Vec::new();
    }

    let result = self.output[self.output_pos..].to_vec();

    self.output.clear();
    self.output_pos = 0;

    result
  }

  /// Returns the number of compressed bytes currently waiting in the
  /// encoder's output buffer.
  pub fn available(&self) -> usize {
    self.output.len() - self.output_pos
  }

  /// Returns whether `finish()` has completed the stream.
  pub fn is_finished(&self) -> bool {
    self.finished
  }

  /// Number of uncompressed bytes consumed by zlib-rs.
  pub fn total_in(&self) -> u64 {
    self.deflate.total_in()
  }

  /// Number of compressed bytes generated by zlib-rs.
  pub fn total_out(&self) -> u64 {
    self.deflate.total_out()
  }

  fn process(&mut self, flush: DeflateFlush) -> Result<(), DeflateError> {
    loop {
      let before_in = self.deflate.total_in();
      let before_out = self.deflate.total_out();

      let status = self
        .deflate
        .compress(&self.input, &mut self.scratch, flush)?;

      let consumed = (self.deflate.total_in() - before_in) as usize;

      let produced = (self.deflate.total_out() - before_out) as usize;

      self.append_scratch(produced);

      if consumed != 0 {
        self.input.drain(..consumed);
      }

      match flush {
        DeflateFlush::NoFlush => {
          if self.input.is_empty() {
            return Ok(());
          }

          // There is still input, so zlib-rs must make
          // progress on another iteration.
          if consumed == 0 && produced == 0 {
            // This should not happen with a non-empty
            // scratch buffer. If it does, continuing would
            // result in an infinite loop.
            return Err(DeflateError::StreamError);
          }

          match status {
            Status::Ok | Status::BufError => {},
            Status::StreamEnd => {
              return Err(DeflateError::StreamError);
            },
          }
        },

        DeflateFlush::SyncFlush => {
          // SyncFlush should have consumed all supplied input
          // when enough output space is available. Our scratch
          // buffer is 32 KiB and gets replenished every call.
          if self.input.is_empty() {
            return Ok(());
          }

          if consumed == 0 && produced == 0 {
            return Err(DeflateError::StreamError);
          }
        },

        _ => {
          return Ok(());
        },
      }
    }
  }

  #[inline]
  fn append_scratch(&mut self, produced: usize) {
    if produced == 0 {
      return;
    }

    self.output.extend_from_slice(&self.scratch[..produced]);
  }
}

#[derive(Debug)]
pub enum DeflateDecoderError {
  Inflate(InflateError),
  Utf8(Utf8Error),
}

impl From<InflateError> for DeflateDecoderError {
  fn from(error: InflateError) -> Self {
    Self::Inflate(error)
  }
}

impl From<Utf8Error> for DeflateDecoderError {
  fn from(error: Utf8Error) -> Self {
    Self::Utf8(error)
  }
}

/// Streaming raw-DEFLATE decoder.
///
/// The compressed input is owned by the decoder and can be replaced
/// with `reset()` without allocating a new `Inflate` state.
///
/// Output is appended to caller-owned `Vec<u8>` / `String` values.
pub struct DeflateDecoder {
  inflate: Inflate,

  input: Vec<u8>,
  input_pos: usize,

  scratch: Vec<u8>,

  finished: bool,
}

impl DeflateDecoder {
  pub fn new(data: Vec<u8>, zlib_header: bool) -> Self {
    Self {
      inflate: Inflate::new(zlib_header, 15),

      input: data,
      input_pos: 0,

      scratch: vec![0; SCRATCH_SIZE],

      finished: false,
    }
  }

  // pub fn default() -> Self {
  //   Self::new(Vec::new(), false)
  // }

  /// Replace the compressed stream and reset the decoder state.
  ///
  /// `data` is moved into the decoder; no copy is performed.
  pub fn reset(&mut self, data: Vec<u8>) {
    self.inflate.reset(false);

    self.input = data;
    self.input_pos = 0;
    self.finished = false;
  }

  /// Reads at most `len` decompressed bytes and appends them to `output`.
  ///
  /// Returns the number of bytes appended.
  ///
  /// If the stream ends before `len` bytes are available, fewer than
  /// `len` bytes may be returned. Use `read_exact()` when exactly `len`
  /// bytes are required.
  pub fn read(&mut self, output: &mut Vec<u8>, len: usize) -> Result<usize, InflateError> {
    if len == 0 || self.finished {
      return Ok(0);
    }

    // Cap the scratch slice at `len` so a large read() request can't
    // pull more decompressed data than the caller asked for.
    let output_len = len.min(SCRATCH_SIZE);

    let before_in = self.inflate.total_in();
    let before_out = self.inflate.total_out();

    let status = self.inflate.decompress(
      &self.input[self.input_pos..],
      &mut self.scratch[..output_len],
      InflateFlush::NoFlush,
    )?;

    let consumed = (self.inflate.total_in() - before_in) as usize;

    let produced = (self.inflate.total_out() - before_out) as usize;

    self.input_pos += consumed;

    output.extend_from_slice(&self.scratch[..produced]);

    if status == Status::StreamEnd {
      self.finished = true;
    }

    // A valid call can produce zero bytes because DEFLATE can
    // buffer internally. However, if there is no input left and
    // we haven't reached StreamEnd, the stream is incomplete.
    if consumed == 0 && produced == 0 && !self.finished {
      if self.input_pos >= self.input.len() {
        return Err(InflateError::DataError);
      }

      return Err(InflateError::StreamError);
    }

    Ok(produced)
  }

  /// Reads exactly `len` decompressed bytes and appends them to
  /// `output`.
  ///
  /// If the stream ends before `len` bytes can be produced, an error
  /// is returned and the bytes that were successfully decoded before
  /// the error remain appended to `output`.
  pub fn read_exact(&mut self, output: &mut Vec<u8>, len: usize) -> Result<(), InflateError> {
    if len == 0 {
      return Ok(());
    }

    let target = output
      .len()
      .checked_add(len)
      .ok_or(InflateError::MemError)?;

    while output.len() < target {
      let remaining = target - output.len();

      let produced = self.read(output, remaining)?;

      if produced == 0 {
        // read() returning zero means that there is no more
        // decompressed data available.
        return Err(if self.finished {
          InflateError::DataError
        } else {
          InflateError::StreamError
        });
      }
    }

    debug_assert_eq!(output.len(), target);

    Ok(())
  }

  /// Reads all remaining decompressed data and appends it to `output`.
  ///
  /// Returns the number of bytes appended.
  pub fn read_to_end(&mut self, output: &mut Vec<u8>) -> Result<usize, InflateError> {
    let before = output.len();

    while !self.finished {
      self.read(output, SCRATCH_SIZE)?;
    }

    Ok(output.len() - before)
  }

  /// Reads all remaining decompressed data as UTF-8 and appends it
  /// to `output`.
  ///
  /// Returns the number of UTF-8 bytes appended to the String.
  pub fn read_to_string(&mut self, output: &mut String) -> Result<usize, DeflateDecoderError> {
    let mut total = 0;

    // A UTF-8 character can be split across two decompression
    // operations, so retain an incomplete trailing sequence here.
    let mut pending = Vec::<u8>::new();

    while !self.finished {
      let before_in = self.inflate.total_in();
      let before_out = self.inflate.total_out();

      let status = self.inflate.decompress(
        &self.input[self.input_pos..],
        &mut self.scratch,
        InflateFlush::NoFlush,
      )?;

      let consumed = (self.inflate.total_in() - before_in) as usize;

      let produced = (self.inflate.total_out() - before_out) as usize;

      self.input_pos += consumed;

      if produced != 0 {
        pending.extend_from_slice(&self.scratch[..produced]);

        match std::str::from_utf8(&pending) {
          Ok(text) => {
            output.push_str(text);
            total += text.len();
            pending.clear();
          },

          Err(error) => {
            let valid = error.valid_up_to();

            if error.error_len().is_some() {
              return Err(DeflateDecoderError::Utf8(error));
            }

            // The bytes are valid except for an incomplete
            // UTF-8 sequence at the end.
            if valid != 0 {
              let text = std::str::from_utf8(&pending[..valid])?;

              output.push_str(text);
              total += text.len();

              pending.drain(..valid);
            }
          },
        }
      }

      if status == Status::StreamEnd {
        self.finished = true;
      }

      if consumed == 0 && produced == 0 && !self.finished {
        if self.input_pos >= self.input.len() {
          return Err(DeflateDecoderError::Inflate(InflateError::DataError));
        }

        return Err(DeflateDecoderError::Inflate(InflateError::StreamError));
      }
    }

    // StreamEnd was reached, so any bytes still pending must
    // represent an incomplete UTF-8 sequence.
    if !pending.is_empty() {
      let error = std::str::from_utf8(&pending).expect_err("pending UTF-8 must be incomplete");

      return Err(DeflateDecoderError::Utf8(error));
    }

    Ok(total)
  }

  pub fn is_finished(&self) -> bool {
    self.finished
  }

  pub fn total_in(&self) -> u64 {
    self.inflate.total_in()
  }

  pub fn total_out(&self) -> u64 {
    self.inflate.total_out()
  }

  pub fn available(&self) -> usize {
    self.input.len().saturating_sub(self.input_pos)
  }
}

impl fmt::Debug for DeflateEncoder {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    f.debug_struct("DeflateEncoder")
      .field("total_in", &self.total_in())
      .field("total_out", &self.total_out())
      .field("finished", &self.finished)
      .finish()
  }
}

impl fmt::Debug for DeflateDecoder {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    f.debug_struct("DeflateDecoder")
      .field("total_in", &self.total_in())
      .field("total_out", &self.total_out())
      .field("finished", &self.finished)
      .finish()
  }
}
